#!bin/bash

sed -i 's/\\u2013/–/g' podcast_log_temp.json
sed -i 's/\\u2014/—/g' podcast_log_temp.json
sed -i 's/\\u00e7/ç/g' podcast_log_temp.json
sed -i 's/\\u00f1/ñ/g' podcast_log_temp.json
sed -i 's/\\u00e9/é/g' podcast_log_temp.json
sed -i 's/\\u00e1/á/g' podcast_log_temp.json
sed -i 's/\\u00f3/ó/g' podcast_log_temp.json
sed -i 's/\\u2026/…/g' podcast_log_temp.json
sed -i 's/\\u2018/‘/g' podcast_log_temp.json
sed -i 's/\\u2019/’/g' podcast_log_temp.json
sed -i 's/\\u201c/“/g' podcast_log_temp.json
sed -i 's/\\u00f1/ñ/g' podcast_log_temp.json
sed -i 's/\\u00e7/ç/g' podcast_log_temp.json
sed -i 's/\\u201d/”/g' podcast_log_temp.json
sed -i 's/\\u00a0/ /g' podcast_log_temp.json
sed -i 's/\\u2028//g' podcast_log_temp.json
sed -i 's/\\u2033/″/g' podcast_log_temp.json
sed -i 's/\\u00ed/í/g' podcast_log_temp.json
sed -i 's/\\u00ad//g' podcast_log_temp.json
sed -i 's/\\u00eb/ë/g' podcast_log_temp.json
sed -i 's/\\u2013/–/g' listen_log_temp.json
sed -i 's/\\u2014/—/g' listen_log_temp.json
sed -i 's/\\u00e7/ç/g' listen_log_temp.json
sed -i 's/\\u00f1/ñ/g' listen_log_temp.json
sed -i 's/\\u00e9/é/g' listen_log_temp.json
sed -i 's/\\u00e1/á/g' listen_log_temp.json
sed -i 's/\\u00f3/ó/g' listen_log_temp.json
sed -i 's/\\u2026/…/g' listen_log_temp.json
sed -i 's/\\u2018/‘/g' listen_log_temp.json
sed -i 's/\\u2019/’/g' listen_log_temp.json
sed -i 's/\\u201c/“/g' listen_log_temp.json
sed -i 's/\\u00f1/ñ/g' listen_log_temp.json
sed -i 's/\\u00e7/ç/g' listen_log_temp.json
sed -i 's/\\u201d/”/g' listen_log_temp.json
sed -i 's/\\u00a0/ /g' listen_log_temp.json
sed -i 's/\\u2028//g' listen_log_temp.json
sed -i 's/\\u2033/″/g' listen_log_temp.json
sed -i 's/\\u00ed/í/g' listen_log_temp.json
sed -i 's/\\u00ad//g' listen_log_temp.json
sed -i 's/\\u00eb/ë/g' listen_log_temp.json
sed -i 's/\\u00bf/¿/g' listen_log_temp.json
sed -i 's/\\u00fa/ú/g' listen_log_temp.json
sed -i 's/\\u00cd/Í/g' listen_log_temp.json
sed -i 's/\\u00e0/à/g' listen_log_temp.json
sed -i 's/\\u0094//g' listen_log_temp.json
sed -i 's/\\u0093//g' listen_log_temp.json
sed -i 's/\\u0085//g' listen_log_temp.json
